
<field:lxr itemname="联系人" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxr>

<field:lxdh itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxdh>

<field:dzyx itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dzyx>

<field:yxms itemname="意向描述" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:yxms>
