<div class="col-md-4 col-sm-6 fl">
              <div class="project-item">
                  <img src="[field:picname/]" >
                  <div class="project-hover">
                      <div class="inside">
                          <h5><a href="[field:arcurl/]">[field:title/]</a></h5>
                          <p>[field:description/]...</p>
                      </div>
                  </div>
              </div>
          </div>