<?php
$z[0]=Array("field","",111,134);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",175,204);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",244,303);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",354,381);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",419,446);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",524,551);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("include","",655,690);
$z[6][4]['filename']="head.htm";
$z[7]=Array("global","",778,805);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("field","",907,936);
$z[8][4]['name']="position";
$z[9]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1035,1120);
$z[9][4]['typeid']="4";
$z[10]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1142,1227);
$z[10][4]['typeid']="6";
$z[11]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1249,1334);
$z[11][4]['typeid']="7";
$z[12]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1356,1441);
$z[12][4]['typeid']="8";
$z[13]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",1463,1548);
$z[13][4]['typeid']="9";
$z[14]=Array("list","\r\n          <li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"  /><span>[field:title/]</span></a></li>\r\n          ",1669,1849);
$z[14][4]['pagesize']="12";
$z[15]=Array("pagelist","",1929,2000);
$z[15][4]['istitem']="index,pre,next,end,end,option,";
$z[15][4]['listsize']="4";
$z[16]=Array("include","",2021,2058);
$z[16][4]['filename']="footer.htm";

?>